version: '3'

services:
  app:
    build: ./
    container_name: app
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - ./.env
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ./:/usr/src/app

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    volumes:
      - ./storage:/data/db